// eslint-disable-next-line @typescript-eslint/no-var-requires
const { VanillaExtractPlugin } = require('@vanilla-extract/webpack-plugin');
// eslint-disable-next-line @typescript-eslint/no-unsafe-assignment, @typescript-eslint/no-var-requires
const MiniCssExtractPlugin = require('mini-css-extract-plugin');

module.exports = {
  // eslint-disable-next-line @typescript-eslint/no-unsafe-call
  plugins: [new VanillaExtractPlugin(), new MiniCssExtractPlugin()],
  module: {
    rules: [
      {
        test: /\.vanilla\.css$/i, // Targets only CSS files generated by vanilla-extract
        use: [
          // eslint-disable-next-line @typescript-eslint/no-unsafe-member-access
          MiniCssExtractPlugin.loader,
          {
            loader: require.resolve('css-loader'),
            options: {
              url: false, // Required as image imports should be handled via JS/TS import statements
            },
          },
        ],
      },
    ],
  },
};
